In [198]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [199]:
# Read data
df = pd.read_csv('covid.csv')
df

date           state     county  population  confirmed  deaths  \
0         1/1/2021         Georgia     Schley        5257        236       2   
1         1/2/2021         Georgia     Schley        5257        239       2   
2         1/3/2021         Georgia     Schley        5257        240       2   
3         1/4/2021         Georgia     Schley        5257        241       2   
4         1/5/2021         Georgia     Schley        5257        243       2   
...            ...             ...        ...         ...        ...     ...   
371521  12/27/2021  North Carolina  Cleveland       97947      19652     322   
371522  12/28/2021  North Carolina  Cleveland       97947      19885     322   
371523  12/29/2021  North Carolina  Cleveland       97947      19945     324   
371524  12/30/2021  North Carolina  Cleveland       97947      20105     324   
371525  12/31/2021  North Carolina  Cleveland       97947      20263     324   

        people_vaccinated  people_fully_vaccinated  school_closing  \
0                       0                        0              -2   
1                       0                        0              -2   
2                       0                        0              -2   
3                       0                        0              -2   
4                       0                        0              -2   
...                   ...                      ...             ...   
371521              60382                    46117               0   
371522              60454                    46132               0   
371523              60529                    46168               0   
371524              60621                    46203               0   
371525              60896                    46271               0   

        workplace_closing  ...  information_campaigns  testing_policy  \
0                       1  ...                      2               3   
1                       1  ...                      2               3   
2                       1  ...                      2               3   
3                       1  ...                      2               3   
4                       1  ...                      2               3   
...                   ...  ...                    ...             ...   
371521                  0  ...                      2               3   
371522                  0  ...                      2               3   
371523                  0  ...                      2               3   
371524                  0  ...                      2               3   
371525                  0  ...                      2               3   

        contact_tracing  facial_coverings  vaccination_policy  \
0                     1                -2                   2   
1                     1                -2                   2   
2                     1                -2                   2   
3                     1                -2                   2   
4                     1                -2                   2   
...                 ...               ...                 ...   
371521                1                 2                   5   
371522                1                 2                   5   
371523                1                 2                   5   
371524                1                 2                   5   
371525                1                 2                   5   

        elderly_people_protection  government_response_index  \
0                              -2                     -56.93   
1                              -2                     -56.93   
2                              -2                     -56.93   
3                              -2                     -56.93   
4                              -2                     -56.93   
...                           ...                        ...   
371521                          1                     -36.46   
371522                          1         

In [200]:
# Read data
df1 = pd.read_csv('NO2.csv')
df1

date       state   county   NO2  DAILY_AQI_NO2
0        1/1/2021  California  Alameda  22.4             21
1        1/2/2021  California  Alameda  16.7             15
2        1/3/2021  California  Alameda  19.2             18
3        1/4/2021  California  Alameda  16.1             15
4        1/5/2021  California  Alameda  22.5             21
...           ...         ...      ...   ...            ...
67580  12/27/2021       Texas   Wilson   6.2              6
67581  12/28/2021       Texas   Wilson   5.6              5
67582  12/29/2021       Texas   Wilson  28.9             26
67583  12/30/2021       Texas   Wilson  11.9             10
67584  12/31/2021       Texas   Wilson   3.4              3

[67585 rows x 5 columns]

In [201]:
# Merge datasets
m = pd.merge(df,df1, on = ['date', 'state', 'county'])
m

date         state    county  population  confirmed  deaths  \
0        1/1/2021  Pennsylvania  Bradford       60323       3088      56   
1        1/2/2021  Pennsylvania  Bradford       60323       3122      56   
2        1/3/2021  Pennsylvania  Bradford       60323       3154      56   
3        1/4/2021  Pennsylvania  Bradford       60323       3169      56   
4        1/5/2021  Pennsylvania  Bradford       60323       3201      57   
...           ...           ...       ...         ...        ...     ...   
65712  12/29/2021       Florida     Duval      957755     168518    2889   
65713  12/30/2021       Florida     Duval      957755     168518    2889   
65714  12/30/2021       Florida     Duval      957755     168518    2889   
65715  12/31/2021       Florida     Duval      957755     176849    2889   
65716  12/31/2021       Florida     Duval      957755     176849    2889   

       people_vaccinated  people_fully_vaccinated  school_closing  \
0                      0                        0              -2   
1                      0                        0              -2   
2                      0                        0              -2   
3                      0                        0              -2   
4                      0                        0              -2   
...                  ...                      ...             ...   
65712             636607                   555397               0   
65713             637591                   556082               0   
65714             637591                   556082               0   
65715             638487                   556602               0   
65716             638487                   556602               0   

       workplace_closing  ...  contact_tracing  facial_coverings  \
0                      2  ...                2                 3   
1                      2  ...                2                 3   
2                      2  ...                2                 3   
3                      1  ...                2                 3   
4                      1  ...                2                 3   
...                  ...  ...              ...               ...   
65712                  0  ...                1                 2   
65713                  0  ...                1                 2   
65714                  0  ...                1                 2   
65715                  0  ...                1                 2   
65716                  0  ...                1                 2   

       vaccination_policy  elderly_people_protection  \
0                       2                          3   
1                       2                          3   
2                       2                          3   
3                       2                          3   
4                       2                          3   
...                   ...                        ...   
65712                   5                          1   
65713                   5                          1   
65714                   5                          1   
65715                   5                          1   
65716                   5                          1   

       government_response_index  stringency_index  containment_health_index  \
0                         -68.12            -63.89                    -70.71   
1                         -68.12            -63.89                    -70.71   
2                         -68.12            -63.89                    -70.71   
3                         -62.92            -54.63                    -64.76   
4                         -62.92            -54.63                    -64.76   
...                          ...               ...                       ...   
65712                     -34.90            -25.00                    -39.88   
65713                     -34.90            -25.00                    -39.88   
65714                     -34.90            -25.00           

In [202]:
m.state.unique()

array(['Pennsylvania', 'Florida', 'California', 'Texas', 'Ohio',
       'Illinois', 'New York', 'North Carolina', 'Michigan', 'Georgia'],
      dtype=object)

In [204]:
m['date'] = pd.to_datetime(m['date'])

In [195]:
m.groupby('state')[['confirmed','NO2']].corr()

confirmed       NO2
state                                        
California     confirmed   1.000000  0.320690
               NO2         0.320690  1.000000
Florida        confirmed   1.000000  0.076822
               NO2         0.076822  1.000000
Georgia        confirmed   1.000000  0.011008
               NO2         0.011008  1.000000
Illinois       confirmed   1.000000  0.554923
               NO2         0.554923  1.000000
Michigan       confirmed   1.000000  0.408263
               NO2         0.408263  1.000000
New York       confirmed   1.000000 -0.280943
               NO2        -0.280943  1.000000
North Carolina confirmed   1.000000  0.427435
               NO2         0.427435  1.000000
Ohio           confirmed   1.000000  0.123164
               NO2         0.123164  1.000000
Pennsylvania   confirmed   1.000000  0.409648
               NO2         0.409648  1.000000
Texas          confirmed   1.000000  0.324729
               NO2         0.324729  1.000000

## California

In [36]:
# Filter data for California
cal = m[m.state == 'California']
cal

date       state    county  population  confirmed  deaths  \
440     1/1/2021  California     Marin      258826       9902     139   
441     1/2/2021  California     Marin      258826      10024     139   
442     1/3/2021  California     Marin      258826      10121     139   
443     1/4/2021  California     Marin      258826      10121     139   
444     1/5/2021  California     Marin      258826      10286     140   
...          ...         ...       ...         ...        ...     ...   
64334  9/26/2021  California  Monterey      434061      49733     573   
64335  9/27/2021  California  Monterey      434061      49872     574   
64336  9/28/2021  California  Monterey      434061      49891     574   
64337  9/29/2021  California  Monterey      434061      49939     574   
64338  9/30/2021  California  Monterey      434061      50161     574   

       people_vaccinated  people_fully_vaccinated  school_closing  \
440                    0                        0              -3   
441                    0                        0              -3   
442                    0                        0              -3   
443                    0                        0              -3   
444                    0                        0              -3   
...                  ...                      ...             ...   
64334             293870                   250889               1   
64335             294027                   251055               1   
64336             294173                   251247               1   
64337             294471                   251496               1   
64338             294957                   251971               1   

       workplace_closing  ...  contact_tracing  facial_coverings  \
440                   -2  ...                2                 3   
441                   -2  ...                2                 3   
442                   -2  ...                2                 3   
443                   -2  ...                2                 3   
444                   -2  ...                2                 3   
...                  ...  ...              ...               ...   
64334                  0  ...                2                 2   
64335                  0  ...                2                 2   
64336                  0  ...                2                 2   
64337                  0  ...                2                 2   
64338                  0  ...                2                 2   

       vaccination_policy  elderly_people_protection  \
440                     2                         -3   
441                     2                         -3   
442                     2                         -3   
443                     2                         -3   
444                     2                         -3   
...                   ...                        ...   
64334                   5                          2   
64335                   5                          2   
64336                   5                          2   
64337                   5                          2   
64338                   5                          2   

       government_response_index  stringency_index  containment_health_index  \
440                       -73.07            -66.20                    -71.01   
441                       -73.07            -66.20                    -71.01   
442                       -73.07            -66.20                    -71.01   
443                       -73.07            -66.20                    -71.01   
444                       -73.07            -66.20                    -71.01   
...                          ...               ...                       ...   
64334                     -54.69            -37.04                    -53.57   
64335                     -54.69            -37.04                    -53.57   
64336                     -54.69            -37.04                    -53.57   
64337           

In [37]:
# Transfor data type 
cal['date'] = pd.to_datetime(cal['date'])

# Select July 
cal_01 = cal[cal['date'].dt.month == 1]
cal_01

C:\Users\My PC\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


date       state    county  population  confirmed  deaths  \
440   2021-01-01  California     Marin      258826       9902     139   
441   2021-01-02  California     Marin      258826      10024     139   
442   2021-01-03  California     Marin      258826      10121     139   
443   2021-01-04  California     Marin      258826      10121     139   
444   2021-01-05  California     Marin      258826      10286     140   
...          ...         ...       ...         ...        ...     ...   
64093 2021-01-27  California  Monterey      434061      38713     274   
64094 2021-01-28  California  Monterey      434061      38853     280   
64095 2021-01-29  California  Monterey      434061      39040     284   
64096 2021-01-30  California  Monterey      434061      39425     285   
64097 2021-01-31  California  Monterey      434061      39425     285   

       people_vaccinated  people_fully_vaccinated  school_closing  \
440                    0                        0              -3   
441                    0                        0              -3   
442                    0                        0              -3   
443                    0                        0              -3   
444                    0                        0              -3   
...                  ...                      ...             ...   
64093              14259                     3256              -3   
64094              14468                     3867              -3   
64095              14732                     4218              -3   
64096              16560                     4375              -3   
64097              17482                     4683              -3   

       workplace_closing  ...  contact_tracing  facial_coverings  \
440                   -2  ...                2                 3   
441                   -2  ...                2                 3   
442                   -2  ...                2                 3   
443                   -2  ...                2                 3   
444                   -2  ...                2                 3   
...                  ...  ...              ...               ...   
64093                 -2  ...                1                 3   
64094                 -2  ...                1                 3   
64095                 -2  ...                1                 3   
64096                 -2  ...                1                 3   
64097                 -2  ...                1                 3   

       vaccination_policy  elderly_people_protection  \
440                     2                         -3   
441                     2                         -3   
442                     2                         -3   
443                     2                         -3   
444                     2                         -3   
...                   ...                        ...   
64093                   2                         -3   
64094                   2                         -3   
64095                   2                         -3   
64096                   2                         -3   
64097                   2                         -3   

       government_response_index  stringency_index  containment_health_index  \
440                       -73.07            -66.20                    -71.01   
441                       -73.07            -66.20                    -71.01   
442                       -73.07            -66.20                    -71.01   
443                       -73.07            -66.20                    -71.01   
444                       -73.07            -66.20                    -71.01   
...                          ...               ...                       ...   
64093                     -68.91            -64.35                    -66.25   
64094                     -68.91            -64.35                    -66.25   
64095                     -68.91            -64.35                    -66.25   
64096           

In [38]:
cal_01 = cal[cal['date'].dt.month == 1]
corr = np.corrcoef(cal_01['confirmed'], cal_01['NO2'])
print (corr)

[[1.        0.3589553]
 [0.3589553 1.       ]]


In [51]:
cal_02 = cal[cal['date'].dt.month == 2]
corr = np.corrcoef(cal_02['confirmed'], cal_02['NO2'])
print (corr)

[[1.         0.35357792]
 [0.35357792 1.        ]]


In [52]:
cal_03 = cal[cal['date'].dt.month == 3]
corr = np.corrcoef(cal_03['confirmed'], cal_03['NO2'])
print (corr)

[[1.         0.30898133]
 [0.30898133 1.        ]]


In [53]:
cal_04 = cal[cal['date'].dt.month == 4]
corr = np.corrcoef(cal_04['confirmed'], cal_04['NO2'])
print (corr)

[[1.        0.3005606]
 [0.3005606 1.       ]]


In [54]:
cal_05 = cal[cal['date'].dt.month == 5]
corr = np.corrcoef(cal_05['confirmed'], cal_05['NO2'])
print (corr)

[[1.         0.22097262]
 [0.22097262 1.        ]]


In [55]:
cal_06 = cal[cal['date'].dt.month == 6]
corr = np.corrcoef(cal_06['confirmed'], cal_06['NO2'])
print (corr)

[[1.         0.29540584]
 [0.29540584 1.        ]]


In [56]:
cal_07 = cal[cal['date'].dt.month == 7]
corr = np.corrcoef(cal_07['confirmed'], cal_07['NO2'])
print (corr)

[[1.         0.33954004]
 [0.33954004 1.        ]]


In [57]:
cal_08 = cal[cal['date'].dt.month == 8]
corr = np.corrcoef(cal_08['confirmed'], cal_08['NO2'])
print (corr)

[[1.         0.31139494]
 [0.31139494 1.        ]]


In [58]:
cal_09 = cal[cal['date'].dt.month == 9]
corr = np.corrcoef(cal_09['confirmed'], cal_09['NO2'])
print (corr)

[[1.         0.29571181]
 [0.29571181 1.        ]]


In [59]:
cal_10 = cal[cal['date'].dt.month == 10]
corr = np.corrcoef(cal_10['confirmed'], cal_10['NO2'])
print (corr)

[[1.         0.39844138]
 [0.39844138 1.        ]]


In [60]:
cal_11 = cal[cal['date'].dt.month == 11]
corr = np.corrcoef(cal_11['confirmed'], cal_11['NO2'])
print (corr)

[[1.         0.46042931]
 [0.46042931 1.        ]]


In [61]:
cal_12 = cal[cal['date'].dt.month == 12]
corr = np.corrcoef(cal_12['confirmed'], cal_12['NO2'])
print (corr)

[[1.         0.41369113]
 [0.41369113 1.        ]]


## Florida

In [63]:
fl = m[m.state == 'Florida']
fl['date'] = pd.to_datetime(fl['date'])
fl


C:\Users\My PC\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


date    state  county  population  confirmed  deaths  \
255   2021-02-02  Florida  Orange     1393452     104286     958   
256   2021-02-03  Florida  Orange     1393452     104620     981   
257   2021-02-04  Florida  Orange     1393452     104988     989   
258   2021-02-05  Florida  Orange     1393452     105724    1000   
259   2021-02-06  Florida  Orange     1393452     106118    1000   
...          ...      ...     ...         ...        ...     ...   
65712 2021-12-29  Florida   Duval      957755     168518    2889   
65713 2021-12-30  Florida   Duval      957755     168518    2889   
65714 2021-12-30  Florida   Duval      957755     168518    2889   
65715 2021-12-31  Florida   Duval      957755     176849    2889   
65716 2021-12-31  Florida   Duval      957755     176849    2889   

       people_vaccinated  people_fully_vaccinated  school_closing  \
255                93920                    27640               1   
256                95715                    29735               1   
257                96319                    30336               1   
258                97957                    33502               1   
259                99615                    37380               1   
...                  ...                      ...             ...   
65712             636607                   555397               0   
65713             637591                   556082               0   
65714             637591                   556082               0   
65715             638487                   556602               0   
65716             638487                   556602               0   

       workplace_closing  ...  contact_tracing  facial_coverings  \
255                   -1  ...                1                -3   
256                   -1  ...                1                -3   
257                   -1  ...                1                -3   
258                   -1  ...                1                -3   
259                   -1  ...                1                -3   
...                  ...  ...              ...               ...   
65712                  0  ...                1                 2   
65713                  0  ...                1                 2   
65714                  0  ...                1                 2   
65715                  0  ...                1                 2   
65716                  0  ...                1                 2   

       vaccination_policy  elderly_people_protection  \
255                     2                          3   
256                     2                          3   
257                     2                          3   
258                     2                          3   
259                     2                          3   
...                   ...                        ...   
65712                   5                          1   
65713                   5                          1   
65714                   5                          1   
65715                   5                          1   
65716                   5                          1   

       government_response_index  stringency_index  containment_health_index  \
255                       -51.98            -45.83                    -52.26   
256                       -51.98            -45.83                    -52.26   
257                       -51.98            -45.83                    -52.26   
258                       -51.98            -45.83                    -52.26   
259                       -51.98            -45.83                    -52.26   
...                          ...               ...                       ...   
65712                     -34.90            -25.00                    -39.88   
65713                     -34.90            -25.00                    -39.88   
65714                     -34.90            -25.00                    -39.88   
65715                     -34.90            -25.00                    -39.88

In [64]:
fl_01 = fl[fl['date'].dt.month == 1]
corr = np.corrcoef(fl_01['confirmed'], fl_01['NO2'])
print (corr)

[[1.         0.21517416]
 [0.21517416 1.        ]]


In [66]:
fl_02 = fl[fl['date'].dt.month == 2]
corr = np.corrcoef(fl_02['confirmed'], fl_02['NO2'])
print (corr)

[[ 1.         -0.08343994]
 [-0.08343994  1.        ]]


In [78]:
fl_03 = fl[fl['date'].dt.month == 3]
corr = np.corrcoef(fl_03['confirmed'], fl_03['NO2'])
print (corr)

[[1.0000000e+00 7.8441517e-05]
 [7.8441517e-05 1.0000000e+00]]


In [68]:
fl_04 = fl[fl['date'].dt.month == 4]
corr = np.corrcoef(fl_04['confirmed'], fl_04['NO2'])
print (corr)

[[ 1.         -0.01360789]
 [-0.01360789  1.        ]]


In [69]:
fl_05 = fl[fl['date'].dt.month == 5]
corr = np.corrcoef(fl_05['confirmed'], fl_05['NO2'])
print (corr)

[[ 1.        -0.0018613]
 [-0.0018613  1.       ]]


In [70]:
fl_06 = fl[fl['date'].dt.month == 6]
corr = np.corrcoef(fl_06['confirmed'], fl_06['NO2'])
print (corr)

[[1.         0.06910376]
 [0.06910376 1.        ]]


In [71]:
fl_07 = fl[fl['date'].dt.month == 7]
corr = np.corrcoef(fl_07['confirmed'], fl_07['NO2'])
print (corr)

[[1.         0.37702964]
 [0.37702964 1.        ]]


In [72]:
fl_08 = fl[fl['date'].dt.month == 8]
corr = np.corrcoef(fl_08['confirmed'], fl_08['NO2'])
print (corr)

[[1.         0.08906173]
 [0.08906173 1.        ]]


In [73]:
fl_09 = fl[fl['date'].dt.month == 9]
corr = np.corrcoef(fl_09['confirmed'], fl_09['NO2'])
print (corr)

[[1.         0.37181494]
 [0.37181494 1.        ]]


In [74]:
fl_10 = fl[fl['date'].dt.month == 10]
corr = np.corrcoef(fl_10['confirmed'], fl_10['NO2'])
print (corr)

[[1.         0.15703802]
 [0.15703802 1.        ]]


In [75]:
fl_11 = fl[fl['date'].dt.month == 11]
corr = np.corrcoef(fl_11['confirmed'], fl_11['NO2'])
print (corr)

[[1.         0.22174785]
 [0.22174785 1.        ]]


In [76]:
fl_12 = fl[fl['date'].dt.month == 12]
corr = np.corrcoef(fl_12['confirmed'], fl_12['NO2'])
print (corr)

[[1.         0.39840268]
 [0.39840268 1.        ]]


## Georgia

In [79]:
ge = m[m.state == 'Georgia']
ge['date'] = pd.to_datetime(ge['date'])
ge

C:\Users\My PC\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


date    state  county  population  confirmed  deaths  \
26525 2021-01-01  Georgia  Fulton     1063937      57846     790   
26526 2021-01-02  Georgia  Fulton     1063937      58560     790   
26527 2021-01-03  Georgia  Fulton     1063937      58951     791   
26528 2021-01-04  Georgia  Fulton     1063937      59387     793   
26529 2021-01-05  Georgia  Fulton     1063937      60131     795   
...          ...      ...     ...         ...        ...     ...   
52324 2021-12-29  Georgia  DeKalb      759297     105114    1409   
52325 2021-12-30  Georgia  DeKalb      759297     106750    1411   
52326 2021-12-30  Georgia  DeKalb      759297     106750    1411   
52327 2021-12-31  Georgia  DeKalb      759297     108164    1411   
52328 2021-12-31  Georgia  DeKalb      759297     108164    1411   

       people_vaccinated  people_fully_vaccinated  school_closing  \
26525                  0                        0              -2   
26526                  0                        0              -2   
26527                  0                        0              -2   
26528                  0                        0              -2   
26529                  0                        0              -2   
...                  ...                      ...             ...   
52324             306574                   270744               1   
52325             307121                   271253               1   
52326             307121                   271253               1   
52327             307755                   271803               1   
52328             307755                   271803               1   

       workplace_closing  ...  contact_tracing  facial_coverings  \
26525                  1  ...                1                -2   
26526                  1  ...                1                -2   
26527                  1  ...                1                -2   
26528                  1  ...                1                -2   
26529                  1  ...                1                -2   
...                  ...  ...              ...               ...   
52324                  0  ...                1                -2   
52325                  0  ...                1                -2   
52326                  0  ...                1                -2   
52327                  0  ...                1                -2   
52328                  0  ...                1                -2   

       vaccination_policy  elderly_people_protection  \
26525                   2                         -2   
26526                   2                         -2   
26527                   2                         -2   
26528                   2                         -2   
26529                   2                         -2   
...                   ...                        ...   
52324                   5                          2   
52325                   5                          2   
52326                   5                          2   
52327                   5                          2   
52328                   5                          2   

       government_response_index  stringency_index  containment_health_index  \
26525                     -56.93             -53.7                    -54.35   
26526                     -56.93             -53.7                    -54.35   
26527                     -56.93             -53.7                    -54.35   
26528                     -56.93             -53.7                    -54.35   
26529                     -56.93             -53.7                    -54.35   
...                          ...               ...                       ...   
52324                     -38.28             -28.7                    -43.75   
52325                     -38.28             -28.7                    -43.75   
52326                     -38.28             -28.7                    -43.75   
52327                     -38.28             -28.7                    -43.75

In [80]:
ge_01 = ge[ge['date'].dt.month == 1]
corr = np.corrcoef(ge_01['confirmed'], ge_01['NO2'])
print (corr)

[[1.         0.15159898]
 [0.15159898 1.        ]]


In [81]:
ge_02 = ge[ge['date'].dt.month == 2]
corr = np.corrcoef(ge_02['confirmed'], ge_02['NO2'])
print (corr)

[[1.         0.14585593]
 [0.14585593 1.        ]]


In [82]:
ge_03 = ge[ge['date'].dt.month == 3]
corr = np.corrcoef(ge_03['confirmed'], ge_03['NO2'])
print (corr)

[[1.         0.11381975]
 [0.11381975 1.        ]]


In [83]:
ge_04 = ge[ge['date'].dt.month == 4]
corr = np.corrcoef(ge_04['confirmed'], ge_04['NO2'])
print (corr)

[[ 1.         -0.01286123]
 [-0.01286123  1.        ]]


In [84]:
ge_05 = ge[ge['date'].dt.month == 5]
corr = np.corrcoef(ge_05['confirmed'], ge_05['NO2'])
print (corr)

[[1.         0.09478942]
 [0.09478942 1.        ]]


In [85]:
ge_06 = ge[ge['date'].dt.month == 6]
corr = np.corrcoef(ge_06['confirmed'], ge_06['NO2'])
print (corr)

[[1.         0.15460095]
 [0.15460095 1.        ]]


In [86]:
ge_07 = ge[ge['date'].dt.month == 7]
corr = np.corrcoef(ge_07['confirmed'], ge_07['NO2'])
print (corr)

[[1.         0.22494898]
 [0.22494898 1.        ]]


In [87]:
ge_08 = ge[ge['date'].dt.month == 8]
corr = np.corrcoef(ge_08['confirmed'], ge_08['NO2'])
print (corr)

[[1.         0.13276371]
 [0.13276371 1.        ]]


In [88]:
ge_09 = ge[ge['date'].dt.month == 9]
corr = np.corrcoef(ge_09['confirmed'], ge_09['NO2'])
print (corr)

[[1.         0.24066044]
 [0.24066044 1.        ]]


In [89]:
ge_10 = ge[ge['date'].dt.month == 10]
corr = np.corrcoef(ge_10['confirmed'], ge_10['NO2'])
print (corr)

[[1.        0.3422235]
 [0.3422235 1.       ]]


In [90]:
ge_11 = ge[ge['date'].dt.month == 11]
corr = np.corrcoef(ge_11['confirmed'], ge_11['NO2'])
print (corr)

[[1.         0.03693421]
 [0.03693421 1.        ]]


In [91]:
ge_12 = ge[ge['date'].dt.month == 12]
corr = np.corrcoef(ge_12['confirmed'], ge_12['NO2'])
print (corr)

[[1.         0.05314377]
 [0.05314377 1.        ]]


## Illinois

In [92]:
il = m[m.state == 'Illinois']
il['date'] = pd.to_datetime(il['date'])
il

C:\Users\My PC\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


date     state    county  population  confirmed  deaths  \
4505  2021-01-01  Illinois  Macoupin       44926       3273      79   
4506  2021-01-02  Illinois  Macoupin       44926       3314      80   
4507  2021-01-03  Illinois  Macoupin       44926       3335      81   
4508  2021-01-04  Illinois  Macoupin       44926       3357      82   
4509  2021-01-05  Illinois  Macoupin       44926       3379      86   
...          ...       ...       ...         ...        ...     ...   
59672 2021-12-31  Illinois      Cook     5150233     821472   12541   
59673 2021-12-31  Illinois      Cook     5150233     821472   12541   
59674 2021-12-31  Illinois      Cook     5150233     821472   12541   
59675 2021-12-31  Illinois      Cook     5150233     821472   12541   
59676 2021-12-31  Illinois      Cook     5150233     821472   12541   

       people_vaccinated  people_fully_vaccinated  school_closing  \
4505                   0                        0              -2   
4506                   0                        0              -2   
4507                   0                        0              -2   
4508                   0                        0              -2   
4509                   0                        0              -2   
...                  ...                      ...             ...   
59672            3924866                  3461565               0   
59673            3924866                  3461565               0   
59674            3924866                  3461565               0   
59675            3924866                  3461565               0   
59676            3924866                  3461565               0   

       workplace_closing  ...  contact_tracing  facial_coverings  \
4505                   1  ...                1                 3   
4506                   1  ...                1                 3   
4507                   1  ...                1                 3   
4508                   1  ...                1                 3   
4509                   1  ...                1                 3   
...                  ...  ...              ...               ...   
59672                  0  ...                2                 2   
59673                  0  ...                2                 2   
59674                  0  ...                2                 2   
59675                  0  ...                2                 2   
59676                  0  ...                2                 2   

       vaccination_policy  elderly_people_protection  \
4505                    2                          1   
4506                    2                          1   
4507                    2                          1   
4508                    2                          1   
4509                    2                          1   
...                   ...                        ...   
59672                   5                          2   
59673                   5                          2   
59674                   5                          2   
59675                   5                          2   
59676                   5                          2   

       government_response_index  stringency_index  containment_health_index  \
4505                      -63.96            -66.67                    -64.17   
4506                      -61.87            -62.96                    -61.79   
4507                      -61.87            -62.96                    -61.79   
4508                      -61.87            -62.96                    -61.79   
4509                      -61.87            -62.96                    -61.79   
...                          ...               ...                       ...   
59672                     -44.79            -25.00                    -45.83   
59673                     -44.79            -25.00                    -45.83   
59674                     -44.79            -25.00                    -45.83   
59675                     -44.79        

In [99]:
il_1 = il[il['date'].dt.month == 1]
corr = np.corrcoef(il_1['confirmed'], il_1['NO2'])
print (corr)

[[1.         0.72931485]
 [0.72931485 1.        ]]


In [100]:
il_2 = il[il['date'].dt.month == 2]
corr = np.corrcoef(il_2['confirmed'], il_2['NO2'])
print (corr)

[[1.         0.78349032]
 [0.78349032 1.        ]]


In [101]:
il_3 = il[il['date'].dt.month == 3]
corr = np.corrcoef(il_3['confirmed'], il_3['NO2'])
print (corr)

[[1.         0.65550264]
 [0.65550264 1.        ]]


In [102]:
il_4 = il[il['date'].dt.month == 4]
corr = np.corrcoef(il_4['confirmed'], il_4['NO2'])
print (corr)

[[1.         0.71102747]
 [0.71102747 1.        ]]


In [103]:
il_5 = il[il['date'].dt.month == 5]
corr = np.corrcoef(il_5['confirmed'], il_5['NO2'])
print (corr)

[[1.        0.6063688]
 [0.6063688 1.       ]]


In [110]:
il_6 = il[il['date'].dt.month == 6]
corr = np.corrcoef(il_6['confirmed'], il_6['NO2'])
print (corr)

[[1.         0.49688899]
 [0.49688899 1.        ]]


In [104]:
il_7 = il[il['date'].dt.month == 7]
corr = np.corrcoef(il_7['confirmed'], il_7['NO2'])
print (corr)

[[1.         0.42438882]
 [0.42438882 1.        ]]


In [105]:
il_8 = il[il['date'].dt.month == 8]
corr = np.corrcoef(il_8['confirmed'], il_8['NO2'])
print (corr)

[[1.         0.63150899]
 [0.63150899 1.        ]]


In [106]:
il_9 = il[il['date'].dt.month == 9]
corr = np.corrcoef(il_9['confirmed'], il_9['NO2'])
print (corr)

[[1.         0.61174877]
 [0.61174877 1.        ]]


In [107]:
il_10 = il[il['date'].dt.month == 10]
corr = np.corrcoef(il_10['confirmed'], il_10['NO2'])
print (corr)

[[1.         0.65812113]
 [0.65812113 1.        ]]


In [108]:
il_11 = il[il['date'].dt.month == 11]
corr = np.corrcoef(il_11['confirmed'], il_11['NO2'])
print (corr)

[[1.         0.72432151]
 [0.72432151 1.        ]]


In [109]:
il_12 = il[il['date'].dt.month == 12]
corr = np.corrcoef(il_12['confirmed'], il_12['NO2'])
print (corr)

[[1.         0.68573379]
 [0.68573379 1.        ]]


## Michigan

In [111]:
mi = m[m.state == 'Michigan']
mi['date'] = pd.to_datetime(mi['date'])
mi

C:\Users\My PC\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


date     state     county  population  confirmed  deaths  \
18919 2021-01-01  Michigan     Ingham      292406      12635     184   
18920 2021-01-02  Michigan     Ingham      292406      12880     190   
18921 2021-01-03  Michigan     Ingham      292406      12880     190   
18922 2021-01-04  Michigan     Ingham      292406      13032     190   
18923 2021-01-05  Michigan     Ingham      292406      13109     193   
...          ...       ...        ...         ...        ...     ...   
63799 2021-12-27  Michigan  Missaukee       15118       2233      46   
63800 2021-12-28  Michigan  Missaukee       15118       2233      46   
63801 2021-12-29  Michigan  Missaukee       15118       2241      46   
63802 2021-12-30  Michigan  Missaukee       15118       2241      46   
63803 2021-12-31  Michigan  Missaukee       15118       2241      46   

       people_vaccinated  people_fully_vaccinated  school_closing  \
18919                  0                        0              -2   
18920                  0                        0              -2   
18921                  0                        0              -2   
18922                  0                        0              -2   
18923                  0                        0              -2   
...                  ...                      ...             ...   
63799               7253                     7015              -1   
63800               7263                     7033              -1   
63801               7265                     7033              -1   
63802               7274                     7043              -1   
63803               7275                     7047              -1   

       workplace_closing  ...  contact_tracing  facial_coverings  \
18919                  2  ...                2                 3   
18920                  2  ...                2                 3   
18921                  2  ...                2                 3   
18922                  2  ...                2                 3   
18923                  2  ...                2                 3   
...                  ...  ...              ...               ...   
63799                  0  ...                2                 2   
63800                  0  ...                2                 2   
63801                  0  ...                2                 2   
63802                  0  ...                2                 2   
63803                  0  ...                2                 2   

       vaccination_policy  elderly_people_protection  \
18919                   2                          3   
18920                   2                          3   
18921                   2                          3   
18922                   2                          3   
18923                   2                          3   
...                   ...                        ...   
63799                   5                          2   
63800                   5                          2   
63801                   5                          2   
63802                   5                          2   
63803                   5                          2   

       government_response_index  stringency_index  containment_health_index  \
18919                     -65.00            -61.11                    -68.93   
18920                     -65.00            -61.11                    -68.93   
18921                     -65.00            -61.11                    -68.93   
18922                     -65.00            -61.11                    -68.93   
18923                     -65.00            -61.11                    -68.93   
...                          ...               ...                       ...   
63799                     -44.27            -26.85                    -47.02   
63800                     -44.27            -26.85                    -47.02   
63801                     -44.27            -26.85                    -47.02   
63802                     -4

In [112]:
mi_1 = mi[mi['date'].dt.month == 1]
corr = np.corrcoef(mi_1['confirmed'], mi_1['NO2'])
print (corr)

[[1.         0.52135382]
 [0.52135382 1.        ]]


In [113]:
mi_2 = mi[mi['date'].dt.month == 2]
corr = np.corrcoef(mi_2['confirmed'], mi_2['NO2'])
print (corr)

[[1.         0.45120605]
 [0.45120605 1.        ]]


In [114]:
mi_3 = mi[mi['date'].dt.month == 3]
corr = np.corrcoef(mi_3['confirmed'], mi_3['NO2'])
print (corr)

[[1.         0.52446472]
 [0.52446472 1.        ]]


In [115]:
mi_4 = mi[mi['date'].dt.month == 4]
corr = np.corrcoef(mi_4['confirmed'], mi_4['NO2'])
print (corr)

[[1.         0.55736887]
 [0.55736887 1.        ]]


In [116]:
mi_5 = mi[mi['date'].dt.month == 5]
corr = np.corrcoef(mi_5['confirmed'], mi_5['NO2'])
print (corr)

[[1.         0.57096784]
 [0.57096784 1.        ]]


In [117]:
mi_6 = mi[mi['date'].dt.month == 6]
corr = np.corrcoef(mi_6['confirmed'], mi_6['NO2'])
print (corr)

[[1.         0.68863716]
 [0.68863716 1.        ]]


In [118]:
mi_7 = mi[mi['date'].dt.month == 7]
corr = np.corrcoef(mi_7['confirmed'], mi_7['NO2'])
print (corr)

[[1.         0.71284491]
 [0.71284491 1.        ]]


In [119]:
mi_8 = mi[mi['date'].dt.month == 8]
corr = np.corrcoef(mi_8['confirmed'], mi_8['NO2'])
print (corr)

[[1.         0.70024343]
 [0.70024343 1.        ]]


In [120]:
mi_9 = mi[mi['date'].dt.month == 9]
corr = np.corrcoef(mi_9['confirmed'], mi_9['NO2'])
print (corr)

[[1.         0.71223947]
 [0.71223947 1.        ]]


In [121]:
mi_10 = mi[mi['date'].dt.month == 10]
corr = np.corrcoef(mi_10['confirmed'], mi_10['NO2'])
print (corr)

[[1.        0.5757834]
 [0.5757834 1.       ]]


In [122]:
mi_11 = mi[mi['date'].dt.month == 11]
corr = np.corrcoef(mi_11['confirmed'], mi_11['NO2'])
print (corr)

[[1.         0.52211263]
 [0.52211263 1.        ]]


In [123]:
mi_12 = mi[mi['date'].dt.month == 12]
corr = np.corrcoef(mi_12['confirmed'], mi_12['NO2'])
print (corr)

[[1.         0.58901547]
 [0.58901547 1.        ]]


## New York											

In [124]:
ny = m[m.state == 'New York']
ny['date'] = pd.to_datetime(ny['date'])
ny

C:\Users\My PC\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


date     state   county  population  confirmed  deaths  \
5933  2021-01-01  New York     Erie      918702      41988    1209   
5934  2021-01-01  New York     Erie      918702      41988    1209   
5935  2021-01-02  New York     Erie      918702      42465    1219   
5936  2021-01-02  New York     Erie      918702      42465    1219   
5937  2021-01-03  New York     Erie      918702      42933    1229   
...          ...       ...      ...         ...        ...     ...   
57888 2021-12-26  New York  Suffolk     1476601     298430    3771   
57889 2021-12-27  New York  Suffolk     1476601     300528    3783   
57890 2021-12-28  New York  Suffolk     1476601     303339    3790   
57891 2021-12-29  New York  Suffolk     1476601     307916    3795   
57892 2021-12-30  New York  Suffolk     1476601     313688    3802   

       people_vaccinated  people_fully_vaccinated  school_closing  \
5933                   0                        0              -2   
5934                   0                        0              -2   
5935                   0                        0              -2   
5936                   0                        0              -2   
5937                   0                        0              -2   
...                  ...                      ...             ...   
57888            1181180                  1050820               1   
57889            1181534                  1051169               1   
57890            1182742                  1051793               1   
57891            1184707                  1052680               1   
57892            1186961                  1053845               1   

       workplace_closing  ...  contact_tracing  facial_coverings  \
5933                  -3  ...                1                 3   
5934                  -3  ...                1                 3   
5935                  -3  ...                1                 3   
5936                  -3  ...                1                 3   
5937                  -3  ...                1                 3   
...                  ...  ...              ...               ...   
57888                  7  ...                7                 7   
57889                  7  ...                7                 7   
57890                  7  ...                7                 7   
57891                  7  ...                7                 7   
57892                  7  ...                7                 7   

       vaccination_policy  elderly_people_protection  \
5933                    2                         -3   
5934                    2                         -3   
5935                    2                         -3   
5936                    2                         -3   
5937                    2                         -3   
...                   ...                        ...   
57888                   7                          7   
57889                   7                          7   
57890                   7                          7   
57891                   7                          7   
57892                   7                          7   

       government_response_index  stringency_index  containment_health_index  \
5933                      -75.16            -72.69                    -71.61   
5934                      -75.16            -72.69                    -71.61   
5935                      -75.16            -72.69                    -71.61   
5936                      -75.16            -72.69                    -71.61   
5937                      -75.16            -72.69                    -71.61   
...                          ...               ...                       ...   
57888                       7.00              7.00                      7.00   
57889                       7.00              7.00                      7.00   
57890                       7.00              7.00                      7.00   
57891                       7.00              7.00  

In [125]:
ny_1 = ny[ny['date'].dt.month == 1]
corr = np.corrcoef(ny_1['confirmed'], ny_1['NO2'])
print (corr)

[[1.         0.09829049]
 [0.09829049 1.        ]]


In [126]:
ny_2 = ny[ny['date'].dt.month == 2]
corr = np.corrcoef(ny_2['confirmed'], ny_2['NO2'])
print (corr)

[[1.        0.2087107]
 [0.2087107 1.       ]]


In [129]:
ny_3 = ny[ny['date'].dt.month == 3]
corr = np.corrcoef(ny_3['confirmed'], ny_3['NO2'])
print (corr)

[[1.         0.31558693]
 [0.31558693 1.        ]]


In [130]:
ny_4 = ny[ny['date'].dt.month == 4]
corr = np.corrcoef(ny_4['confirmed'], ny_4['NO2'])
print (corr)

[[1.         0.33144787]
 [0.33144787 1.        ]]


In [131]:
ny_5 = ny[ny['date'].dt.month == 5]
corr = np.corrcoef(ny_5['confirmed'], ny_5['NO2'])
print (corr)

[[1.         0.46557582]
 [0.46557582 1.        ]]


In [132]:
ny_6 = ny[ny['date'].dt.month == 6]
corr = np.corrcoef(ny_6['confirmed'], ny_6['NO2'])
print (corr)

[[1.         0.35349372]
 [0.35349372 1.        ]]


In [133]:
ny_7 = ny[ny['date'].dt.month == 7]
corr = np.corrcoef(ny_7['confirmed'], ny_7['NO2'])
print (corr)

[[ 1.         -0.54046371]
 [-0.54046371  1.        ]]


In [134]:
ny_8 = ny[ny['date'].dt.month == 8]
corr = np.corrcoef(ny_8['confirmed'], ny_8['NO2'])
print (corr)

[[ 1.         -0.50718105]
 [-0.50718105  1.        ]]


In [135]:
ny_9 = ny[ny['date'].dt.month == 9]
corr = np.corrcoef(ny_9['confirmed'], ny_9['NO2'])
print (corr)

[[ 1.         -0.57933073]
 [-0.57933073  1.        ]]


In [136]:
ny_10 = ny[ny['date'].dt.month == 10]
corr = np.corrcoef(ny_10['confirmed'], ny_10['NO2'])
print (corr)

[[ 1.         -0.39677677]
 [-0.39677677  1.        ]]


In [137]:
ny_11 = ny[ny['date'].dt.month == 11]
corr = np.corrcoef(ny_11['confirmed'], ny_11['NO2'])
print (corr)

[[ 1.         -0.33061735]
 [-0.33061735  1.        ]]


In [138]:
ny_12 = ny[ny['date'].dt.month == 12]
corr = np.corrcoef(ny_12['confirmed'], ny_12['NO2'])
print (corr)

[[ 1.         -0.19290942]
 [-0.19290942  1.        ]]


## North Carolina											

In [139]:
nc = m[m.state == 'North Carolina']
nc['date'] = pd.to_datetime(nc['date'])
nc

C:\Users\My PC\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


date           state   county  population  confirmed  deaths  \
8170  2021-01-01  North Carolina  Forsyth      382295      20643     221   
8171  2021-01-02  North Carolina  Forsyth      382295      21208     225   
8172  2021-01-03  North Carolina  Forsyth      382295      21367     225   
8173  2021-01-04  North Carolina  Forsyth      382295      21527     231   
8174  2021-01-05  North Carolina  Forsyth      382295      21691     231   
...          ...             ...      ...         ...        ...     ...   
63444 2021-12-27  North Carolina    Rowan      142088      28194     488   
63445 2021-12-28  North Carolina    Rowan      142088      28593     488   
63446 2021-12-29  North Carolina    Rowan      142088      28675     488   
63447 2021-12-30  North Carolina    Rowan      142088      28922     488   
63448 2021-12-31  North Carolina    Rowan      142088      29102     492   

       people_vaccinated  people_fully_vaccinated  school_closing  \
8170                   0                        0              -2   
8171                   0                        0              -2   
8172                   0                        0              -2   
8173                   0                        0              -2   
8174                   0                        0              -2   
...                  ...                      ...             ...   
63444              76401                    59497               0   
63445              76492                    59538               0   
63446              76602                    59572               0   
63447              76743                    59644               0   
63448              77036                    59803               0   

       workplace_closing  ...  contact_tracing  facial_coverings  \
8170                   2  ...                1                 4   
8171                   2  ...                1                 4   
8172                   2  ...                1                 4   
8173                   2  ...                1                 4   
8174                   2  ...                1                 4   
...                  ...  ...              ...               ...   
63444                  0  ...                1                 2   
63445                  0  ...                1                 2   
63446                  0  ...                1                 2   
63447                  0  ...                1                 2   
63448                  0  ...                1                 2   

       vaccination_policy  elderly_people_protection  \
8170                    1                          2   
8171                    1                          2   
8172                    1                          2   
8173                    1                          2   
8174                    1                          2   
...                   ...                        ...   
63444                   5                          1   
63445                   5                          1   
63446                   5                          1   
63447                   5                          1   
63448                   5                          1   

       government_response_index  stringency_index  containment_health_index  \
8170                      -63.23            -64.81                    -63.33   
8171                      -63.23            -64.81                    -63.33   
8172                      -63.23            -64.81                    -63.33   
8173                      -63.23            -64.81                    -63.33   
8174                      -63.23            -64.81                    -63.33   
...                          ...               ...                       ...   
63444                     -36.46            -27.78                    -41.67   
63445                     -36.46            -27.78                    -41.67   
63446                     -36.46            -27.78          

In [140]:
nc_1 = nc[nc['date'].dt.month == 1]
corr = np.corrcoef(nc_1['confirmed'], nc_1['NO2'])
print (corr)

[[1.         0.63142851]
 [0.63142851 1.        ]]


In [141]:
nc_2 = nc[nc['date'].dt.month == 2]
corr = np.corrcoef(nc_2['confirmed'], nc_2['NO2'])
print (corr)

[[1.         0.56146077]
 [0.56146077 1.        ]]


In [142]:
nc_3 = nc[nc['date'].dt.month == 3]
corr = np.corrcoef(nc_3['confirmed'], nc_3['NO2'])
print (corr)

[[1.        0.4652672]
 [0.4652672 1.       ]]


In [143]:
nc_4 = nc[nc['date'].dt.month == 4]
corr = np.corrcoef(nc_4['confirmed'], nc_4['NO2'])
print (corr)

[[1.         0.55837352]
 [0.55837352 1.        ]]


In [144]:
nc_5 = nc[nc['date'].dt.month == 5]
corr = np.corrcoef(nc_5['confirmed'], nc_5['NO2'])
print (corr)

[[1.         0.55285271]
 [0.55285271 1.        ]]


In [145]:
nc_6 = nc[nc['date'].dt.month == 6]
corr = np.corrcoef(nc_6['confirmed'], nc_6['NO2'])
print (corr)

[[1.         0.37035802]
 [0.37035802 1.        ]]


In [146]:
nc_7 = nc[nc['date'].dt.month == 7]
corr = np.corrcoef(nc_7['confirmed'], nc_7['NO2'])
print (corr)

[[1.         0.50501271]
 [0.50501271 1.        ]]


In [147]:
nc_8 = nc[nc['date'].dt.month == 8]
corr = np.corrcoef(nc_8['confirmed'], nc_8['NO2'])
print (corr)

[[1.         0.58450226]
 [0.58450226 1.        ]]


In [148]:
nc_9 = nc[nc['date'].dt.month == 9]
corr = np.corrcoef(nc_9['confirmed'], nc_9['NO2'])
print (corr)

[[1.         0.68160592]
 [0.68160592 1.        ]]


In [149]:
nc_10 = nc[nc['date'].dt.month == 10]
corr = np.corrcoef(nc_10['confirmed'], nc_10['NO2'])
print (corr)

[[1.         0.48698408]
 [0.48698408 1.        ]]


In [150]:
nc_11 = nc[nc['date'].dt.month == 11]
corr = np.corrcoef(nc_11['confirmed'], nc_11['NO2'])
print (corr)

[[1.         0.49744128]
 [0.49744128 1.        ]]


In [151]:
nc_12 = nc[nc['date'].dt.month == 12]
corr = np.corrcoef(nc_12['confirmed'], nc_12['NO2'])
print (corr)

[[1.         0.39263863]
 [0.39263863 1.        ]]


## Ohio

In [152]:
oh = m[m.state == 'Ohio']
oh['date'] = pd.to_datetime(oh['date'])
oh

C:\Users\My PC\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


date state    county  population  confirmed  deaths  \
3807  2021-01-01  Ohio  Franklin     1316756      84050     698   
3808  2021-01-01  Ohio  Franklin     1316756      84050     698   
3809  2021-01-02  Ohio  Franklin     1316756      85553     698   
3810  2021-01-02  Ohio  Franklin     1316756      85553     698   
3811  2021-01-03  Ohio  Franklin     1316756      86446     698   
...          ...   ...       ...         ...        ...     ...   
40582 2021-12-27  Ohio   Belmont       67006      11182     243   
40583 2021-12-28  Ohio   Belmont       67006      11255     244   
40584 2021-12-29  Ohio   Belmont       67006      11338     244   
40585 2021-12-30  Ohio   Belmont       67006      11422     244   
40586 2021-12-31  Ohio   Belmont       67006      11473     246   

       people_vaccinated  people_fully_vaccinated  school_closing  \
3807                   0                        0              -2   
3808                   0                        0              -2   
3809                   0                        0              -2   
3810                   0                        0              -2   
3811                   0                        0              -2   
...                  ...                      ...             ...   
40582              34591                    30878               0   
40583              34670                    30926               0   
40584              34700                    30959               0   
40585              34761                    30996               0   
40586              34824                    31040               0   

       workplace_closing  ...  contact_tracing  facial_coverings  \
3807                   1  ...                2                 3   
3808                   1  ...                2                 3   
3809                   1  ...                2                 3   
3810                   1  ...                2                 3   
3811                   1  ...                2                 3   
...                  ...  ...              ...               ...   
40582                  0  ...                2                -2   
40583                  0  ...                2                -2   
40584                  0  ...                2                -2   
40585                  0  ...                2                -2   
40586                  0  ...                2                -2   

       vaccination_policy  elderly_people_protection  \
3807                    2                          2   
3808                    2                          2   
3809                    2                          2   
3810                    2                          2   
3811                    2                          2   
...                   ...                        ...   
40582                   5                          2   
40583                   5                          2   
40584                   5                          2   
40585                   5                          2   
40586                   5                          2   

       government_response_index  stringency_index  containment_health_index  \
3807                      -61.35            -58.33                    -64.76   
3808                      -61.35            -58.33                    -64.76   
3809                      -61.35            -58.33                    -64.76   
3810                      -61.35            -58.33                    -64.76   
3811                      -61.35            -58.33                    -64.76   
...                          ...               ...                       ...   
40582                     -44.01            -25.00                    -44.94   
40583                     -44.01            -25.00                    -44.94   
40584                     -44.01            -25.00                    -44.94   
40585                     -44.01            -25.00                    -44.94   
40586   

In [153]:
oh_1 = oh[oh['date'].dt.month == 1]
corr = np.corrcoef(oh_1['confirmed'], oh_1['NO2'])
print (corr)

[[1.         0.10684209]
 [0.10684209 1.        ]]


In [154]:
oh_2 = oh[oh['date'].dt.month == 2]
corr = np.corrcoef(oh_2['confirmed'], oh_2['NO2'])
print (corr)

[[1.         0.19359458]
 [0.19359458 1.        ]]


In [155]:
oh_3 = oh[oh['date'].dt.month == 3]
corr = np.corrcoef(oh_3['confirmed'], oh_3['NO2'])
print (corr)

[[1.         0.13079037]
 [0.13079037 1.        ]]


In [156]:
oh_4 = oh[oh['date'].dt.month == 4]
corr = np.corrcoef(oh_4['confirmed'], oh_4['NO2'])
print (corr)

[[1.        0.2573277]
 [0.2573277 1.       ]]


In [157]:
oh_5 = oh[oh['date'].dt.month == 5]
corr = np.corrcoef(oh_5['confirmed'], oh_5['NO2'])
print (corr)

[[1.         0.28380829]
 [0.28380829 1.        ]]


In [158]:
oh_6 = oh[oh['date'].dt.month == 6]
corr = np.corrcoef(oh_6['confirmed'], oh_6['NO2'])
print (corr)

[[1.         0.27787422]
 [0.27787422 1.        ]]


In [159]:
oh_7 = oh[oh['date'].dt.month == 7]
corr = np.corrcoef(oh_7['confirmed'], oh_7['NO2'])
print (corr)

[[ 1.         -0.16262232]
 [-0.16262232  1.        ]]


In [160]:
oh_8 = oh[oh['date'].dt.month == 8]
corr = np.corrcoef(oh_8['confirmed'], oh_8['NO2'])
print (corr)

[[1.        0.2903438]
 [0.2903438 1.       ]]


In [161]:
oh_9 = oh[oh['date'].dt.month == 9]
corr = np.corrcoef(oh_9['confirmed'], oh_9['NO2'])
print (corr)

[[1.         0.24320723]
 [0.24320723 1.        ]]


In [162]:
oh_10 = oh[oh['date'].dt.month == 10]
corr = np.corrcoef(oh_10['confirmed'], oh_10['NO2'])
print (corr)

[[ 1.         -0.01547531]
 [-0.01547531  1.        ]]


In [163]:
oh_11 = oh[oh['date'].dt.month == 11]
corr = np.corrcoef(oh_11['confirmed'], oh_11['NO2'])
print (corr)

[[1.         0.18444282]
 [0.18444282 1.        ]]


In [164]:
oh_12 = oh[oh['date'].dt.month == 12]
corr = np.corrcoef(oh_12['confirmed'], oh_12['NO2'])
print (corr)

[[ 1.         -0.00158713]
 [-0.00158713  1.        ]]


## Pennsylvania	

In [165]:
pn = m[m.state == 'Pennsylvania']
pn['date'] = pd.to_datetime(pn['date'])
pn

C:\Users\My PC\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


date         state     county  population  confirmed  deaths  \
0     2021-01-01  Pennsylvania   Bradford       60323       3088      56   
1     2021-01-02  Pennsylvania   Bradford       60323       3122      56   
2     2021-01-03  Pennsylvania   Bradford       60323       3154      56   
3     2021-01-04  Pennsylvania   Bradford       60323       3169      56   
4     2021-01-05  Pennsylvania   Bradford       60323       3201      57   
...          ...           ...        ...         ...        ...     ...   
65032 2021-12-29  Pennsylvania  Allegheny     1216045     172136    2715   
65033 2021-12-30  Pennsylvania  Allegheny     1216045     174116    2724   
65034 2021-12-30  Pennsylvania  Allegheny     1216045     174116    2724   
65035 2021-12-31  Pennsylvania  Allegheny     1216045     176336    2725   
65036 2021-12-31  Pennsylvania  Allegheny     1216045     176336    2725   

       people_vaccinated  people_fully_vaccinated  school_closing  \
0                      0                        0              -2   
1                      0                        0              -2   
2                      0                        0              -2   
3                      0                        0              -2   
4                      0                        0              -2   
...                  ...                      ...             ...   
65032             920967                   804480              -2   
65033             923501                   805631              -2   
65034             923501                   805631              -2   
65035             923599                   805652              -2   
65036             923599                   805652              -2   

       workplace_closing  ...  contact_tracing  facial_coverings  \
0                      2  ...                2                 3   
1                      2  ...                2                 3   
2                      2  ...                2                 3   
3                      1  ...                2                 3   
4                      1  ...                2                 3   
...                  ...  ...              ...               ...   
65032                  0  ...                2                -3   
65033                  0  ...                2                -3   
65034                  0  ...                2                -3   
65035                  0  ...                2                -3   
65036                  0  ...                2                -3   

       vaccination_policy  elderly_people_protection  \
0                       2                          3   
1                       2                          3   
2                       2                          3   
3                       2                          3   
4                       2                          3   
...                   ...                        ...   
65032                   5                          2   
65033                   5                          2   
65034                   5                          2   
65035                   5                          2   
65036                   5                          2   

       government_response_index  stringency_index  containment_health_index  \
0                         -68.12            -63.89                    -70.71   
1                         -68.12            -63.89                    -70.71   
2                         -68.12            -63.89                    -70.71   
3                         -62.92            -54.63                    -64.76   
4                         -62.92            -54.63                    -64.76   
...                          ...               ...                       ...   
65032                     -50.26            -30.56                    -50.30   
65033                     -50.26            -30.56                    -50.30   
65034                     -50.26            -30.56          

In [166]:
pn_1 = pn[pn['date'].dt.month == 1]
corr = np.corrcoef(pn_1['confirmed'], pn_1['NO2'])
print (corr)

[[1.         0.43237534]
 [0.43237534 1.        ]]


In [167]:
pn_2 = pn[pn['date'].dt.month == 2]
corr = np.corrcoef(pn_2['confirmed'], pn_2['NO2'])
print (corr)

[[1.         0.46702751]
 [0.46702751 1.        ]]


In [168]:
pn_3 = pn[pn['date'].dt.month == 3]
corr = np.corrcoef(pn_3['confirmed'], pn_3['NO2'])
print (corr)

[[1.         0.50691433]
 [0.50691433 1.        ]]


In [169]:
pn_4 = pn[pn['date'].dt.month == 4]
corr = np.corrcoef(pn_4['confirmed'], pn_4['NO2'])
print (corr)

[[1.         0.42897058]
 [0.42897058 1.        ]]


In [170]:
pn_5 = pn[pn['date'].dt.month == 5]
corr = np.corrcoef(pn_5['confirmed'], pn_5['NO2'])
print (corr)

[[1.         0.43608878]
 [0.43608878 1.        ]]


In [171]:
pn_6 = pn[pn['date'].dt.month == 6]
corr = np.corrcoef(pn_6['confirmed'], pn_6['NO2'])
print (corr)

[[1.         0.42958668]
 [0.42958668 1.        ]]


In [172]:
pn_7 = pn[pn['date'].dt.month == 7]
corr = np.corrcoef(pn_7['confirmed'], pn_7['NO2'])
print (corr)

[[1.         0.47230182]
 [0.47230182 1.        ]]


In [173]:
pn_8 = pn[pn['date'].dt.month == 8]
corr = np.corrcoef(pn_8['confirmed'], pn_8['NO2'])
print (corr)

[[1.         0.49389759]
 [0.49389759 1.        ]]


In [174]:
pn_9 = pn[pn['date'].dt.month == 9]
corr = np.corrcoef(pn_9['confirmed'], pn_9['NO2'])
print (corr)

[[1.         0.47704255]
 [0.47704255 1.        ]]


In [175]:
pn_10 = pn[pn['date'].dt.month == 10]
corr = np.corrcoef(pn_10['confirmed'], pn_10['NO2'])
print (corr)

[[1.         0.41184908]
 [0.41184908 1.        ]]


In [176]:
pn_11 = pn[pn['date'].dt.month == 11]
corr = np.corrcoef(pn_11['confirmed'], pn_11['NO2'])
print (corr)

[[1.        0.3244474]
 [0.3244474 1.       ]]


In [177]:
pn_12 = pn[pn['date'].dt.month == 12]
corr = np.corrcoef(pn_12['confirmed'], pn_12['NO2'])
print (corr)

[[1.        0.5016718]
 [0.5016718 1.       ]]


## Texas

In [178]:
tx = m[m.state == 'Texas']
tx['date'] = pd.to_datetime(tx['date'])
tx

C:\Users\My PC\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


date  state  county  population  confirmed  deaths  \
802   2021-01-01  Texas  Karnes       15601       1275      21   
803   2021-01-02  Texas  Karnes       15601       1275      21   
804   2021-01-03  Texas  Karnes       15601       1275      21   
805   2021-01-04  Texas  Karnes       15601       1275      21   
806   2021-01-05  Texas  Karnes       15601       1322      23   
...          ...    ...     ...         ...        ...     ...   
62613 2021-12-29  Texas  Travis     1273954     132862    1500   
62614 2021-12-30  Texas  Travis     1273954     133466    1500   
62615 2021-12-30  Texas  Travis     1273954     133466    1500   
62616 2021-12-31  Texas  Travis     1273954     133466    1500   
62617 2021-12-31  Texas  Travis     1273954     133466    1500   

       people_vaccinated  people_fully_vaccinated  school_closing  \
802                    0                        0              -2   
803                    0                        0              -2   
804                    0                        0              -2   
805                    0                        0              -2   
806                    0                        0              -2   
...                  ...                      ...             ...   
62613             980691                   843859               0   
62614             982263                   844795               0   
62615             982263                   844795               0   
62616             982378                   844801               0   
62617             982378                   844801               0   

       workplace_closing  ...  contact_tracing  facial_coverings  \
802                   -2  ...                1                 3   
803                   -2  ...                1                 3   
804                   -2  ...                1                 3   
805                   -2  ...                1                 3   
806                   -2  ...                1                 3   
...                  ...  ...              ...               ...   
62613                  0  ...                1                -2   
62614                  0  ...                1                -2   
62615                  0  ...                1                -2   
62616                  0  ...                1                -2   
62617                  0  ...                1                -2   

       vaccination_policy  elderly_people_protection  \
802                     2                          2   
803                     2                          2   
804                     2                          2   
805                     2                          2   
806                     2                          2   
...                   ...                        ...   
62613                   5                          2   
62614                   5                          2   
62615                   5                          2   
62616                   5                          2   
62617                   5                          2   

       government_response_index  stringency_index  containment_health_index  \
802                       -56.67            -56.48                    -57.62   
803                       -56.67            -56.48                    -57.62   
804                       -56.67            -56.48                    -57.62   
805                       -56.67            -56.48                    -57.62   
806                       -56.67            -56.48                    -57.62   
...                          ...               ...                       ...   
62613                     -40.89            -25.00                    -41.37   
62614                     -40.89            -25.00                    -41.37   
62615                     -40.89            -25.00                    -41.37   
62616                     -40.89            -25.00                    -41.37   
62617               

In [179]:
tx_1 = tx[tx['date'].dt.month == 1]
corr = np.corrcoef(tx_1['confirmed'], tx_1['NO2'])
print (corr)

[[1.         0.41469197]
 [0.41469197 1.        ]]


In [180]:
tx_2 = tx[tx['date'].dt.month == 2]
corr = np.corrcoef(tx_2['confirmed'], tx_2['NO2'])
print (corr)

[[1.        0.3580932]
 [0.3580932 1.       ]]


In [181]:
tx_3 = tx[tx['date'].dt.month == 3]
corr = np.corrcoef(tx_3['confirmed'], tx_3['NO2'])
print (corr)

[[1.         0.41381717]
 [0.41381717 1.        ]]


In [182]:
tx_4 = tx[tx['date'].dt.month == 4]
corr = np.corrcoef(tx_4['confirmed'], tx_4['NO2'])
print (corr)

[[1.        0.4023354]
 [0.4023354 1.       ]]


In [183]:
tx_5 = tx[tx['date'].dt.month == 5]
corr = np.corrcoef(tx_5['confirmed'], tx_5['NO2'])
print (corr)

[[1.         0.37242166]
 [0.37242166 1.        ]]


In [184]:
tx_6 = tx[tx['date'].dt.month == 6]
corr = np.corrcoef(tx_6['confirmed'], tx_6['NO2'])
print (corr)

[[1.         0.34960182]
 [0.34960182 1.        ]]


In [185]:
tx_7 = tx[tx['date'].dt.month == 7]
corr = np.corrcoef(tx_7['confirmed'], tx_7['NO2'])
print (corr)

[[1.         0.41683864]
 [0.41683864 1.        ]]


In [186]:
tx_8 = tx[tx['date'].dt.month == 8]
corr = np.corrcoef(tx_8['confirmed'], tx_8['NO2'])
print (corr)

[[1.         0.37857807]
 [0.37857807 1.        ]]


In [187]:
tx_9 = tx[tx['date'].dt.month == 9]
corr = np.corrcoef(tx_9['confirmed'], tx_9['NO2'])
print (corr)

[[1.         0.31749783]
 [0.31749783 1.        ]]


In [188]:
tx_10 = tx[tx['date'].dt.month == 10]
corr = np.corrcoef(tx_10['confirmed'], tx_10['NO2'])
print (corr)

[[1.        0.3307622]
 [0.3307622 1.       ]]


In [189]:
tx_11 = tx[tx['date'].dt.month == 11]
corr = np.corrcoef(tx_11['confirmed'], tx_11['NO2'])
print (corr)

[[1.         0.26898142]
 [0.26898142 1.        ]]


In [190]:
tx_12 = tx[tx['date'].dt.month == 12]
corr = np.corrcoef(tx_12['confirmed'], tx_12['NO2'])
print (corr)

[[1.         0.36477091]
 [0.36477091 1.        ]]
